filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: 'tools/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'
    environment:
        php:
            version: 7.0.7